import "./globals.css";
import Providers from "./providers";

export const metadata = {
  title: "COMO-Online store for bags",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <Providers>
        {children}
      </Providers>
      </body>
    </html>
  );
}
